name = "merk2-scrapper-frontend"
compatibility_date = "2024-06-01"
pages_build_output_dir = "dist"

# KV namespace binding for production
[[kv_namespaces]]
binding = "CAR_LISTINGS"
id = "677b8c8790fc44a58eaad0a3f2f89c3f"

# Environment variables for production
[env.production.vars]
NODE_ENV = "production"

# KV namespace binding for development/preview
[env.production]
[[env.production.kv_namespaces]]
binding = "CAR_LISTINGS"
id = "677b8c8790fc44a58eaad0a3f2f89c3f"

