name = "ml-autos-scraper"
main = "src/autos-scraper.js"
compatibility_date = "2024-06-01"

[[kv_namespaces]]
binding = "CAR_LISTINGS"
id = "677b8c8790fc44a58eaad0a3f2f89c3f"

[observability.logs]
enabled = true



